version: "3.3"  # optional since v1.27.0

networks:
    web:
        external: true
    internal:
        external: false

services:
    db:
        image: postgres:13
        restart: on-failure
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - internal
        ports:
            - 5432:5432

    divvy:
        restart: on-failure
        build: .
        labels:
            - traefik.http.routers.divvy.rule=Host(`api.plellworks.com`)
            - traefik.http.routers.divvy.tls=true
            - traefik.http.routers.divvy.tls.certresolver=lets-encrypt
            - traefik.port=80
        networks:
            - internal
            - web
        depends_on:
            - db
        volumes:
            - tokens:/divvy/tokens
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable


volumes:
    tokens: {}
    db_data:
        driver: local