version: "3.3"  # optional since v1.27.0

networks:
    web:
        external: true
    internal:
        external: false

services:
    divvy:
        build: .
        labels:
        - traefik.http.routers.divvy.rule=Host(`api.plellworks.com`)
        - traefik.http.routers.divvy.tls=true
        - traefik.http.routers.divvy.tls.certresolver=lets-encrypt
        - traefik.port=80
        networks:
        - internal
        - web
