[http.routers.api]
  rule = "Host(`monitor.api.davidplell.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
[http.routers.api.tls]
  certResolver = "lets-encrypt"